name: (1/2) Deploy Laravel - Upload Files

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Laravel Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WEBGLOBE_SSH_HOST }}
          username: ${{ secrets.WEBGLOBE_SSH_USER }}
          password: ${{ secrets.WEBGLOBE_SSH_PASSWORD }}
          port: ${{ secrets.WEBGLOBE_SSH_PORT }}
          source: "."
          target: "public_html/beer_quiz"

      - name: Set Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEBGLOBE_SSH_HOST }}
          username: ${{ secrets.WEBGLOBE_SSH_USER }}
          password: ${{ secrets.WEBGLOBE_SSH_PASSWORD }}
          port: ${{ secrets.WEBGLOBE_SSH_PORT }}
          script: |
            cd public_html/beer_quiz
            chmod -R 775 storage bootstrap/cache
            echo "✅ Soubory úspěšně nahrány a oprávnění nastavena."
