name: Deploy Laravel App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VH_SSH_HOST }}
          username: ${{ secrets.VH_SSH_USER }}
          key: ${{ secrets.VH_SSH_KEY }}
          port: 22
          debug: true
          script: |
            cd /www/hosting/beer-quiz/www
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link